[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[functions]
  external_node_modules = ["*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
